# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

options:
  machineType: 'N1_HIGHCPU_32'
  diskSizeGb: '512'
  env: [ 'HOME=/h' ]
  volumes:
    - name: 'home'
      path: '/h'

# Variables that can be overridden from the `gcloud builds ...` command using
# the `--substitutions=_FOO=bar` flag.
substitutions:
  _DISTRO: 'unknown'
  _BUILD_NAME: 'unknown'
  _CACHE_BUCKET: 'cloud-cpp-cloudbuild-cache'
  _CACHE_TYPE: '${_PR_NUMBER:-base}'

timeout: 3600s

steps:
  # Builds the docker image that will be used by the following steps. Uses
  # kaniko to cache each layer to speed up building of the image.
- name: 'gcr.io/kaniko-project/executor:edge'
  args: [
    '--context=dir:///workspace/ci',
    '--dockerfile=ci/cloudbuild/${_DISTRO}.Dockerfile',
    '--cache=true',
    '--destination=gcr.io/${PROJECT_ID}/google-cloud-cpp-cloudbuild-docker/${_DISTRO}-image:${BUILD_ID}',
  ]

  # Restores the cached homedir into /h in parallel with the previous step.
  # First tries to fetch cache-type-specific path (i.e., a cache specific to
  # the current PR, if a PR triggered build), followed by the "base" cache for
  # the specified build name. Failures are ignored.
- name: 'gcr.io/cloud-builders/gsutil'
  waitFor: [ '-' ]
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    cache_urls=(
      'gs://${_CACHE_BUCKET}/google-cloud-cpp/${_CACHE_TYPE}/${_DISTRO}-${_BUILD_NAME}'
      'gs://${_CACHE_BUCKET}/google-cloud-cpp/base/${_DISTRO}-${_BUILD_NAME}'
    )
    for url in "${cache_urls[@]}"; do
      echo "Fetching cache url ${url}"
      gsutil -q -m rsync -r -c -e "${url}/h" /h && break
    done
    exit 0

  # Runs the specified build inside the docker image that was created in the
  # first step.
- name: 'gcr.io/${PROJECT_ID}/google-cloud-cpp-cloudbuild-docker/${_DISTRO}-image:${BUILD_ID}'
  entrypoint: 'ci/cloudbuild/build.sh'
  args: [ '${_BUILD_NAME}' ]

  # Removes files in /h with non-UTF-8 filenames to prevent `gsutil rsync` from
  # crashing: https://github.com/GoogleCloudPlatform/gsutil/issues/922
- name: 'gcr.io/${PROJECT_ID}/google-cloud-cpp-cloudbuild-docker/${_DISTRO}-image:${BUILD_ID}'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    for f in $(find /h); do
      if ! iconv -f UTF-8 <<<"${f}" > /dev/null; then
        printf "Removing non-UTF-8 filename: %s\n" "${f}"
        rm -rf -- "${f}"
      fi
    done

  # Caches the homedir, /h, in the specified GCS bucket.
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-c'
  - |-
    du -sh /h
    printf "Total files: %d\n" $(find /home/jgm | wc -l)
    url='gs://${_CACHE_BUCKET}/google-cloud-cpp/${_CACHE_TYPE}/${_DISTRO}-${_BUILD_NAME}'
    gsutil -q -m rsync -r -c -e /h "${url}/h"
