filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  push:
    branch: ^(master|main|v\d+\..*)$
name: bazel-clang-ci
substitutions:
  _BUILD_NAME: bazel-clang
  _DISTRO: fedora
  _TRIGGER_TYPE: ci
tags:
- ci
