filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  pullRequest:
    branch: ^(master|main|v\d+\..*)$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: check-abi-pr
substitutions:
  _BUILD_NAME: check-abi
  _DISTRO: fedora
  _TRIGGER_TYPE: pr
tags:
- pr
