filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  push:
    branch: ^(master|main|preview-.*|v\d+\..*)$
name: cmake-gcc-ci
substitutions:
  _BUILD_NAME: cmake-gcc
  _DISTRO: fedora
  _TRIGGER_TYPE: ci
tags:
- ci
