filename: ci/cloudbuild/cloudbuild.yaml
github:
  name: google-cloud-cpp
  owner: googleapis
  pullRequest:
    branch: ^(master|main|preview-.*|v\d+\..*)$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
name: cmake-gcc-pr
substitutions:
  _BUILD_NAME: cmake-gcc
  _DISTRO: fedora
  _TRIGGER_TYPE: pr
tags:
- pr
