apiVersion: cloud-build-notifiers/v1
kind: BigQueryNotifier
metadata:
  name: google-cloud-cpp-bigquery-notifier
spec:
  notification:
    filter: has(build.build_trigger_id)
    delivery:
      table: projects/936212892354/datasets/cloudbuild/tables/google_cloud_cpp
