# For an overview of the syntax of this file, see
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

# This workflow triggers only on pushes (merges) to the master branch. This
# workflow does not trigger on PRs. See pr.yml for that workflow.
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
    # the rest of the steps
    - uses: actions/checkout@v2

    # Caches (and restores) the bazel build output.
    - name: Cache bazel build results
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-master
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Build the code
      run: bazel build ...

    - name: Test the code
      run: bazel test --test_output=errors --test_tag_filters=-integration-test ...

