# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For an overview of the syntax of this file, see
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
    # the rest of the steps
    - uses: actions/checkout@v2

    # The Caching step differs based on whether this is a push or a pull
    # request. The only difference is that for PRs, we also look for a
    # restore-key containing the `github.base_ref`, so that a PR can use the
    # cache from the most recent CI build that was done on the base_ref (e.g.,
    # "master"). We implement this with two steps that are selectively
    # enabled/disabled based on the existence of the `github.base_ref` context.
    # This is basically an if-else block.
    - name: Cache bazel build results (push)
      if: !github.base_ref
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}

    - name: Cache bazel build results (PR)
      if: github.base_ref
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}

    - name: Build the code
      run: bazel build ...

    - name: Test the code
      run: bazel test --test_output=errors --test_tag_filters=-integration-test ...

