# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For an overview of the syntax of this file, see
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: PR

# This workflow triggers only on Pull Requests.
on:
  pull_request:
    branches:
      - master
      - v*.*.*

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
    # the rest of the steps
    - uses: actions/checkout@v2

    # Caches (and restores) the bazel build output.
    # This workflow is only run on pull requests (to master) and it caches
    # using the `github.ref` context, which is the name of the branch, but is
    # also looks for existing cache keys using `github.base_ref`, which in most
    # cases will be "master", so PRs will be able to use the cache from the
    # previously run CI build.
    - name: Cache bazel build results
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.base_ref }}

    - name: Build the code
      run: bazel build ...

    - name: Test the code
      run: bazel test --test_output=errors --test_tag_filters=-integration-test ...
